### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by mwt** [ph-rast/bmgarch#13]
Hi,

For openjournals/joss-reviews/issues/3452, you need some sort of community guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

These could be in your readme or in some other file.

**Comment by ph-rast** [comment]
Hi @mwt, I added a section "[community Guidelines](https://github.com/ph-rast/bmgarch#community-guidelines)" at the bottom of the README. I've made use of the `tidyverse` templates - let me know if this is what you were looking for.

**Comment by mwt** [comment]
That looks good to me. Thanks!
