### ISSUE TITLE
Namespace in Imports field not imported from: ‘RcppParallel’

### ISSUE THREAD

**Issue by ph-rast** [ph-rast/bmgarch#16]
@andrjohns I was going to submit the current version in master to CRAN but I get this note form R CMD Check: 
```
Namespace in Imports field not imported from: ‘RcppParallel’
    All declared Imports should be used.
```
I added RcppParallel to the DESCRIPTION file, as per point 2 in [MC-stan discourse](https://discourse.mc-stan.org/t/r-package-maintainers-using-stan-please-read/24131)
The `RcppParellelLibs()` is called in src/Makevars but it will not show in the NAMESPACE and adding it manually will be futile as it NAMESPACE gets regenerated with every call to `devtools::document()`

Any idea on how to get RcppParellel to show up in NAMESPACE? Or any other solution?

**Comment by andrjohns** [comment]
@hsbadr did we have a recommended approach for this or is the NOTE unavoidable?

**Comment by hsbadr** [comment]
> @hsbadr did we have a recommended approach for this or is the NOTE unavoidable?

Now that TBB is built into `libStanHeaders`, there's no need to use `RcppParellelLibs()` anymore.

It can be tested with:
```r
remove.packages(c("StanHeaders", "rstan"))
install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

**Comment by ph-rast** [comment]
Thank you @andrjohns @hsbadr - check looks good now!
